name: Build and Run AiCodeReview By Main Maven Jar

on:
  # 当main分支有推送时触发
  push:
    branches:
      - main
  # 当main分支有拉取请求时触发
  pull_request:
    branches:
      - main

jobs:
  build:
    # 指定环境
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出仓库
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # 第二步：设置JDK 8环境
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      # 第三步：创建libs目录
      - name: Create libs directory
        run: mkdir -p ./libs

      # 第四步：下载ai-code-review-sdk JAR文件
      - name: Download ai-code-review-sdk JAR
        run: wget -O ./libs/ai-code-review-sdk-1.0.jar https://github.com/JasperLinnn/ai-code-review/releases/download/v1.0/ai-code-review-sdk-1.0.jar

      # 第五步：获取仓库名称
      - name: Get repository name
        id: repo-name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      # 第六步：获取分支名称
      - name: Get branch name
        id: branch-name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      # 第七步：获取提交作者
      - name: Get commit author
        id: commit-author
        run: echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')" >> $GITHUB_ENV

      # 第八步：获取提交信息
      - name: Get commit message
        id: commit-message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      # 第九步：打印仓库名称、分支名称、提交作者和提交信息
      - name: Print repository, branch name, commit author, and commit message
        run: |
          echo "Repository name is ${{ env.REPO_NAME }}"
          echo "Branch name is ${{ env.BRANCH_NAME }}"
          echo "Commit author is ${{ env.COMMIT_AUTHOR }}"
          echo "Commit message is ${{ env.COMMIT_MESSAGE }}"     

      # 第十步：运行代码审查
      - name: Run code Review
        run: java -jar ./libs/ai-code-review-sdk-1.0.jar
        env:
          CODE_TOKEN: ${{ secrets.CODE_TOKEN }}
          AI_API_HOST: ${{ secrets.AI_API_HOST }}
          AI_API_SECRET: ${{ secrets.AI_API_SECRET }}
          AI_MODEL: ${{ secrets.AI_MODEL }}
          FEISHU_ROBOT_WEBHOOK: ${{ secrets.FEISHU_ROBOT_WEBHOOK }}
          REVIEW_LOG_URI: ${{ secrets.REVIEW_LOG_URI }}
          COMMIT_PROJECT: ${{ env.REPO_NAME }}
          COMMIT_BRANCH: ${{ env.BRANCH_NAME }}
          COMMIT_AUTHOR: ${{ env.COMMIT_AUTHOR }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}